[2025-03-16T20:12:25.060+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: frequent_flyers.create_schema scheduled__2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16T20:12:25.066+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: frequent_flyers.create_schema scheduled__2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16T20:12:25.066+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-16T20:12:25.073+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_schema> on 2025-03-15 00:00:00+00:00
[2025-03-16T20:12:25.075+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2025-03-16T20:12:25.077+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'frequent_flyers', 'create_schema', 'scheduled__2025-03-15T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/frequent_flyers.py', '--cfg-path', '/tmp/tmpxpbu_cfv']
[2025-03-16T20:12:25.079+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask create_schema
[2025-03-16T20:12:25.088+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-16T20:12:25.110+0000] {task_command.py:415} INFO - Running <TaskInstance: frequent_flyers.create_schema scheduled__2025-03-15T00:00:00+00:00 [running]> on host b70acf7f0e92
[2025-03-16T20:12:25.161+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='frequent_flyers' AIRFLOW_CTX_TASK_ID='create_schema' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-15T00:00:00+00:00'
[2025-03-16T20:12:25.162+0000] {sql.py:274} INFO - Executing: 
CREATE SCHEMA IF NOT EXISTS presentation;
[2025-03-16T20:12:25.168+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-16T20:12:25.174+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-16T20:12:25.179+0000] {sql.py:418} INFO - Running statement: 
CREATE SCHEMA IF NOT EXISTS presentation;, parameters: None
[2025-03-16T20:12:25.186+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=frequent_flyers, task_id=create_schema, execution_date=20250315T000000, start_date=20250316T201225, end_date=20250316T201225
[2025-03-16T20:12:25.220+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-16T20:12:25.240+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-16T20:25:12.944+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: frequent_flyers.create_schema scheduled__2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16T20:25:12.949+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: frequent_flyers.create_schema scheduled__2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16T20:25:12.949+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-16T20:25:12.957+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_schema> on 2025-03-15 00:00:00+00:00
[2025-03-16T20:25:12.960+0000] {standard_task_runner.py:57} INFO - Started process 231 to run task
[2025-03-16T20:25:12.962+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'frequent_flyers', 'create_schema', 'scheduled__2025-03-15T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/frequent_flyers.py', '--cfg-path', '/tmp/tmp3w4nhk6p']
[2025-03-16T20:25:12.964+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask create_schema
[2025-03-16T20:25:12.975+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-16T20:25:13.002+0000] {task_command.py:415} INFO - Running <TaskInstance: frequent_flyers.create_schema scheduled__2025-03-15T00:00:00+00:00 [running]> on host 711ad4f92c48
[2025-03-16T20:25:13.055+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='frequent_flyers' AIRFLOW_CTX_TASK_ID='create_schema' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-15T00:00:00+00:00'
[2025-03-16T20:25:13.055+0000] {sql.py:274} INFO - Executing: 
CREATE SCHEMA IF NOT EXISTS presentation;
[2025-03-16T20:25:13.062+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-16T20:25:13.070+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-16T20:25:13.075+0000] {sql.py:418} INFO - Running statement: 
CREATE SCHEMA IF NOT EXISTS presentation;, parameters: None
[2025-03-16T20:25:13.084+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=frequent_flyers, task_id=create_schema, execution_date=20250315T000000, start_date=20250316T202512, end_date=20250316T202513
[2025-03-16T20:25:13.103+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-16T20:25:13.121+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
